CREATE SCHEMA IF NOT EXISTS gcp_db;

CREATE TABLE gcp_db.fornecedor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    cnpj VARCHAR(18) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL,
    telefone VARCHAR(20)
);

CREATE TABLE gcp_db.nota_fiscal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_arquivo VARCHAR(255) NOT NULL,
    caminho_arquivo VARCHAR(512) NOT NULL,
    data_envio TIMESTAMP NOT NULL,
    fornecedor_id BIGINT,
    CONSTRAINT fk_nota_fiscal_fornecedor FOREIGN KEY (fornecedor_id) REFERENCES gcp_db.fornecedor(id)
);